name = "sampler2D"
uuid = "a1864d65-8aa8-4399-b2e0-feaca5c9a14e"
authors = ["Jose Manuel de Frutos"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
